namespace: ddosify

backendHost: https://api.ddosify.com:443
monitoringID: <monitoringID>  # required
logLevel: 1   # zero log levels: -1: trace, 0: debug, 1: info, 2: warn, 3: error, 4: fatal, 5: panic

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 400Mi

image: ddosify/alaz:v0.2.0
imagePullPolicy: IfNotPresent
containerPort: 8181
podAnnotations: {}

# enable prometheus node exporter metrics (cpu, memory, network, disk, etc.)
metricsEnabled: true

# enable eBPF for k8s network data to create a service map
eBPFEnabled: true
