apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: alaz-backend
  name: alaz-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      service: alaz-backend
  strategy: {}
  template:
    metadata:
      labels:
        service: alaz-backend
    spec:
      containers:
        - args:
            - /workspace/start_scripts/start_app_onprem.sh
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
          image: ddosify/selfhosted_alaz_backend:1.0.5
          name: alaz-backend
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: alaz-backend
  name: alaz-backend
spec:
  ports:
    - name: "8008"
      port: 8008
      targetPort: 8008
  selector:
    service: alaz-backend
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: alaz-backend-celery-beat
  name: alaz-backend-celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      service: alaz-backend-celery-beat
  strategy: {}
  template:
    metadata:
      labels:
        service: alaz-backend-celery-beat
    spec:
      containers:
        - args:
            - /workspace/start_scripts/start_celery_beat.sh
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
          image: ddosify/selfhosted_alaz_backend:1.0.5
          name: alaz-backend-celery-beat
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: alaz-backend-celery-worker-1
  name: alaz-backend-celery-worker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      service: alaz-backend-celery-worker-1
  strategy: {}
  template:
    metadata:
      labels:
        service: alaz-backend-celery-worker-1
    spec:
      containers:
        - args:
            - /workspace/start_scripts/start_celery_worker.sh
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
          image: ddosify/selfhosted_alaz_backend:1.0.5
          name: alaz-backend-celery-worker-1
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: alaz-backend-celery-worker-2
  name: alaz-backend-celery-worker-2
spec:
  replicas: 1
  selector:
    matchLabels:
      service: alaz-backend-celery-worker-2
  strategy: {}
  template:
    metadata:
      labels:
        service: alaz-backend-celery-worker-2
    spec:
      containers:
        - args:
            - /workspace/start_scripts/start_celery_worker.sh
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
          image: ddosify/selfhosted_alaz_backend:1.0.5
          name: alaz-backend-celery-worker-2
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
status: {}