apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: hammermanager
  name: hammermanager
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hammermanager
  strategy: {}
  template:
    metadata:
      labels:
        service: hammermanager
    spec:
      containers:
        - args:
            - /workspace/start_scripts/start_app.sh
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
          image: ddosify/selfhosted_hammermanager:1.2.2
          imagePullPolicy: IfNotPresent
          name: hammermanager
          ports:
            - containerPort: 8001
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: hammermanager
  name: hammermanager
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    service: hammermanager
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: hammermanager-celery-beat
  name: hammermanager-celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hammermanager-celery-beat
  strategy: {}
  template:
    metadata:
      labels:
        service: hammermanager-celery-beat
    spec:
      containers:
        - args:
            - /workspace/start_scripts/start_celery_beat.sh
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
          image: ddosify/selfhosted_hammermanager:1.2.2
          imagePullPolicy: IfNotPresent
          name: hammermanager-celery-beat
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: hammermanager-celery-worker
  name: hammermanager-celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hammermanager-celery-worker
  strategy: {}
  template:
    metadata:
      labels:
        service: hammermanager-celery-worker
    spec:
      containers:
        - args:
            - /workspace/start_scripts/start_celery_worker.sh
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
          image: ddosify/selfhosted_hammermanager:1.2.2
          imagePullPolicy: IfNotPresent
          name: hammermanager-celery-worker
          resources: {}
      restartPolicy: Always
status: {}
