apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: hammerdebug
  name: hammerdebug
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hammerdebug
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: hammerdebug
    spec:
      initContainers:
        - name: check-dependencies
          image: {{ .Values.images.initContainerBusybox }}
          command: ['sh', '-c', 'until nc -z hammermanager 8001; do echo waiting for dependencies; sleep 2; done;']
      containers:
        - env:
            - name: IS_DEBUG
              value: "true"
          envFrom:
            - configMapRef:
                name: env
          image: {{ .Values.images.hammer }}
          imagePullPolicy: IfNotPresent
          name: hammerdebug
          resources: {}
      restartPolicy: Always
