apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ddosify
  labels:
    service: hammer
  name: hammer
spec:
  replicas: {{ .Values.hammerReplicas }}
  selector:
    matchLabels:
      service: hammer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: hammer
    spec:
      containers:
        - env:
            - name: INFLUXDB_URL
              valueFrom:
                configMapKeyRef:
                  key: INFLUXDB_URL
                  name: env
            - name: DOCKER_INFLUXDB_INIT_ORG
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_INFLUXDB_INIT_ORG
                  name: env
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
                  name: env
          image: ddosify/selfhosted_hammer:1.4.2
          name: hammer
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
