apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: rabbitmq-job
  name: rabbitmq-job
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq-job
  strategy: {}
  template:
    metadata:
      labels:
        service: rabbitmq-job
    spec:
      containers:
        - name: rabbitmq-job
          image: {{ .Values.images.rabbitmq }}
          ports:
            - containerPort: 5672
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: rabbitmq-job
  name: rabbitmq-job
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    service: rabbitmq-job
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: rabbitmq-celery
  name: rabbitmq-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq-celery
  strategy: {}
  template:
    metadata:
      labels:
        service: rabbitmq-celery
    spec:
      containers:
        - name: rabbitmq-celery
          image: {{ .Values.images.rabbitmq }}
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: rabbitmq-celery
  name: rabbitmq-celery
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    service: rabbitmq-celery
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: rabbitmq-celery-backend
  name: rabbitmq-celery-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq-celery-backend
  strategy: {}
  template:
    metadata:
      labels:
        service: rabbitmq-celery-backend
    spec:
      containers:
        - name: rabbitmq-celery-backend
          image: {{ .Values.images.rabbitmq }}
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: rabbitmq-celery-backend
  name: rabbitmq-celery-backend
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    service: rabbitmq-celery-backend
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: rabbitmq-celery-alaz-backend
  name: rabbitmq-celery-alaz-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq-celery-alaz-backend
  strategy: {}
  template:
    metadata:
      labels:
        service: rabbitmq-celery-alaz-backend
    spec:
      containers:
        - name: rabbitmq-celery-alaz-backend
          image: {{ .Values.images.rabbitmq }}
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: rabbitmq-celery-alaz-backend
  name: rabbitmq-celery-alaz-backend
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    service: rabbitmq-celery-alaz-backend
status:
  loadBalancer: {}
