apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend
  name: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      service: backend
  strategy: {}
  template:
    metadata:
      labels:
        service: backend
    spec:
      initContainers:
        - name: check-dependencies
          image: {{ .Values.images.initContainerBusybox }}
          command: ['sh', '-c', 'until nc -z -w4 {{ .Values.postgres.host }} {{ .Values.postgres.port }}; do echo waiting for dependencies; sleep 1; done;']
      containers:
        - args:
            - /workspace/start_scripts/start_app_onprem.sh
          envFrom:
            - configMapRef:
                name: env
          image: {{ .Values.images.backend }}
          name: backend
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend
  name: backend
spec:
  ports:
    - name: "8008"
      port: 8008
      targetPort: 8008
  selector:
    service: backend
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-celery-beat
  name: backend-celery-beat
spec:
  replicas: {{ .Values.backend.celeryBeatReplicas }}
  selector:
    matchLabels:
      service: backend-celery-beat
  strategy: {}
  template:
    metadata:
      labels:
        service: backend-celery-beat
    spec:
      initContainers:
        - name: check-dependencies
          image: {{ .Values.images.initContainerBusybox }}
          command: ['sh', '-c', 'until nc -z -w4 backend 8008 && nc -z rabbitmq 5672; do echo waiting for dependencies; sleep 1; done;']
      containers:
        - args:
            - /workspace/start_scripts/start_celery_beat.sh
          envFrom:
            - configMapRef:
                name: env
          image: {{ .Values.images.backend }}
          name: backend-celery-beat
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-celery-worker
  name: backend-celery-worker
spec:
  replicas: {{ .Values.backend.celeryWorkerReplicas }}
  selector:
    matchLabels:
      service: backend-celery-worker
  strategy: {}
  template:
    metadata:
      labels:
        service: backend-celery-worker
    spec:
      initContainers:
        - name: check-dependencies
          image: {{ .Values.images.initContainerBusybox }}
          command: ['sh', '-c', 'until nc -z -w4 backend 8008 && nc -z rabbitmq 5672; do echo waiting for dependencies; sleep 1; done;']
      containers:
        - args:
            - /workspace/start_scripts/start_celery_worker.sh
          envFrom:
            - configMapRef:
                name: env
          image: {{ .Values.images.backend }}
          name: backend-celery-worker
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
status: {}