apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: hammer
  name: hammer
spec:
  replicas: {{ .Values.hammer.replicas }}
  selector:
    matchLabels:
      service: hammer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: hammer
    spec:
      initContainers:
        - name: check-dependencies
          image: {{ .Values.images.initContainerBusybox }}
          command: ['sh', '-c', 'until nc -z -w4 hammermanager 8001; do echo waiting for dependencies; sleep 1; done;']
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: {{ .Values.images.hammer }}
          name: hammer
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
