apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: hammermanager
  name: hammermanager
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hammermanager
  strategy: {}
  template:
    metadata:
      labels:
        service: hammermanager
    spec:
      initContainers:
        - name: check-dependencies
          image: {{ .Values.images.initContainerBusybox }}
          command: ['sh', '-c', 'until nc -z postgres {{ .Values.postgres.port }}; do echo waiting for dependencies; sleep 2; done;']
      containers:
        - args:
            - /workspace/start_scripts/start_app.sh
          envFrom:
            - configMapRef:
                name: env
          image: anteon/selfhosted_hammermanager:1.2.4
          imagePullPolicy: IfNotPresent
          name: hammermanager
          ports:
            - containerPort: 8001
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: hammermanager
  name: hammermanager
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    service: hammermanager
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: hammermanager-celery-beat
  name: hammermanager-celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hammermanager-celery-beat
  strategy: {}
  template:
    metadata:
      labels:
        service: hammermanager-celery-beat
    spec:
      initContainers:
        - name: check-dependencies
          image: {{ .Values.images.initContainerBusybox }}
          command: ['sh', '-c', 'until nc -z hammermanager 8001 && nc -z rabbitmq-celery 5672 && nc -z rabbitmq-job 5672; do echo waiting for dependencies; sleep 2; done;']
      containers:
        - args:
            - /workspace/start_scripts/start_celery_beat.sh
          envFrom:
            - configMapRef:
                name: env
          image: anteon/selfhosted_hammermanager:1.2.4
          imagePullPolicy: IfNotPresent
          name: hammermanager-celery-beat
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: hammermanager-celery-worker
  name: hammermanager-celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hammermanager-celery-worker
  strategy: {}
  template:
    metadata:
      labels:
        service: hammermanager-celery-worker
    spec:
      initContainers:
        - name: check-dependencies
          image: {{ .Values.images.initContainerBusybox }}
          command: ['sh', '-c', 'until nc -z hammermanager 8001 && nc -z rabbitmq-celery 5672 && nc -z rabbitmq-job 5672; do echo waiting for dependencies; sleep 2; done;']
      containers:
        - args:
            - /workspace/start_scripts/start_celery_worker.sh
          envFrom:
            - configMapRef:
                name: env
          image: anteon/selfhosted_hammermanager:1.2.4
          imagePullPolicy: IfNotPresent
          name: hammermanager-celery-worker
          resources: {}
      restartPolicy: Always
status: {}
