apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: redis-backend
  name: redis-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: redis-backend
    spec:
      containers:
        - name: redis-backend
          image: {{ .Values.images.redis }}
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis-backend
  name: redis-backend
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    service: redis-backend
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: redis-alaz-backend
  name: redis-alaz-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis-alaz-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: redis-alaz-backend
    spec:
      containers:
        - name: redis-alaz-backend
          image: {{ .Values.images.redis }}
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis-alaz-backend
  name: redis-alaz-backend
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    service: redis-alaz-backend
status:
  loadBalancer: {}
