ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: anteon.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

hammerReplicas: 1

service:
  name: nginx-service
  port: 80
  nodePort: 30000

influxDB:
  # If you set external to true, this means that you will manage the influxdb server yourself
  # Recommended influxDB version: 2.6.1
  # You must set url, apiToken and org
  # and you must create the buckets manually:
  #   - hammerBucket
  #   - hammerBucketDetailed
  #   - hammerBucketIteration
  # username and password are only used if external is false
  external: false
  url: "http://influxdb:8086"
  apiToken: "5yR2qD5zCqqvjwCKKXojnPviQaB87w9JcGweVChXkhWRL"
  org: "ddosify"
  username: "admin" # only used if external is false
  password: "ChangeMe" # only used if external is false
  initBuckerName: "hammerBucket"
  initMode: "setup"

postgres:
  # If you set external to true, this means that you will manage the postgres server yourself
  # Recommended postgres version: 13.6
  # You must set host, port, username and password
  # and you must create the databases manually
  #   - backend
  #   - hammermanager
  external: false
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "ChangeMe"

pvc:
  influxDB:
    storageClassName: ""
    size: 5Gi
  postgres:
    storageClassName: ""
    size: 5Gi
  seaweedfs:
    storageClassName: ""
    size: 30Gi

images:
  alazBackend: anteon/selfhosted_alaz_backend:1.0.6
  backend: anteon/selfhosted_backend:2.6.11
  frontend: anteon/selfhosted_frontend:2.7.4
  hammer: anteon/selfhosted_hammer:1.4.3
  hammermanager: anteon/selfhosted_hammermanager:1.2.4
  influxdb: influxdb:2.6.1-alpine
  nginx: nginx:1.25.4-alpine
  postgres: postgres:13.6-alpine
  prometheus: prom/prometheus:v2.37.9
  rabbitmq: rabbitmq:3.13.0-alpine
  redis: redis:7.2.4-alpine
  seaweedfs: chrislusf/seaweedfs:3.56
  initContainerBusybox: busybox:1.36.1
