apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/selfhosted-ddosify: "true"
        service: backend
    spec:
      containers:
        - args:
            - /workspace/start_scripts/start_app_onprem.sh
          env:
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
                  name: env
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_INFLUXDB_INIT_PASSWORD
                  name: env
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_INFLUXDB_INIT_USERNAME
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
          image: ddosify/selfhosted_backend:1.1.0
          name: backend
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend
  name: backend
spec:
  ports:
    - name: "8008"
      port: 8008
      targetPort: 8008
  selector:
    service: backend
status:
  loadBalancer: {}
