apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ddosify
  labels:
    service: hammer
  name: hammer
spec:
  replicas: {{ .Values.hammerReplicas }}
  selector:
    matchLabels:
      service: hammer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/selfhosted-ddosify: "true"
        service: hammer
    spec:
      containers:
        - env:
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
                  name: env
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_INFLUXDB_INIT_PASSWORD
                  name: env
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DOCKER_INFLUXDB_INIT_USERNAME
                  name: env
          image: ddosify/selfhosted_hammer:1.3.0
          name: hammer
          imagePullPolicy: IfNotPresent
          resources: {}
      restartPolicy: Always
